version: '3.8'

services:
  template_service:
    build: ./services/template_service
    container_name: template_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./services/template_service:/app

  context-adapter:
    build: ./services/context_adapter
    ports:
      - "8010:8010"
    environment:
      MQTT_HOST: mqtt
    depends_on:
      - mosquitto

  dashboard:
    build: ./ui/dashboard
    ports:
      - "5173:80"
    depends_on:
      - context-adapter

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=smartport
      - POSTGRES_PASSWORD=smartport
      - POSTGRES_DB=smartport
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  timeseries:
    build: ./services/timeseries
    depends_on:
      - postgres
      - mosquitto
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: smartport
      PGDATABASE: postgres
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    ports:
      - "8020:8020"

  # sensor-sim:
  #   build: ./tools/sensor_sim
  #   environment:
  #     MQTT_HOST: mqtt
  #     MQTT_PORT: 1883
  #   depends_on:
  #     - mosquitto

  keycloak:
    image: keycloak:24
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data

  wiremock:
    image: wiremock/wiremock:3
    ports:
      - "9090:8080"
    volumes:
      - wiremock_data:/home/wiremock

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  twin-core:
    build: ./services/twin_core
    ports:
      - "8030:8030"
    environment:
      WS_ENDPOINT: ws://context-adapter:8010
      REDIS_HOST: redis
    depends_on:
      - redis
      - context-adapter

volumes:
  pgdata:
  mosquitto_data:
  mosquitto_log:
  keycloak_data:
  wiremock_data:
