scrape_configs:
  - job_name: 'context-adapter'
    static_configs:
      - targets: ['context-adapter:8010']
    metrics_path: /metrics
  - job_name: 'timeseries'
    static_configs:
      - targets: ['timeseries:8020']
    metrics_path: /metrics
  - job_name: 'twin-core'
    static_configs:
      - targets: ['twin-core:8030']
    metrics_path: /metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8081']
    metrics_path: /metrics
