http:
  routers:
    api:
      rule: "Host(`ports360.online`) && PathPrefix(`/api`)"
      service: context-adapter
      entryPoints: [web]

    gql:
      rule: "Host(`ports360.online`) && PathPrefix(`/gql`)"
      service: twin-core
      entryPoints: [web]

    db:
      rule: "Host(`ports360.online`) && PathPrefix(`/db`)"
      service: timeseries
      entryPoints: [web]

    dashboard:
      rule: "Host(`ports360.online`) && PathPrefix(`/`)"
      service: dashboard
      entryPoints: [web]

  services:
    context-adapter:
      loadBalancer:
        servers:
          - url: http://context-adapter:8010
    twin-core:
      loadBalancer:
        servers:
          - url: http://twin-core:8030
    timeseries:
      loadBalancer:
        servers:
          - url: http://timeseries:8020
    dashboard:
      loadBalancer:
        servers:
          - url: http://dashboard:80
