http:
  routers:
    api:
      rule: "Host(`ports360.online`) && PathPrefix(`/api`)"
      service: context-adapter
      entryPoints: [web]
      middlewares: [strip-api]

    gql:
      rule: "Host(`ports360.online`) && PathPrefix(`/gql`)"
      service: twin-core
      entryPoints: [web]
      middlewares: [strip-gql]

    db:
      rule: "Host(`ports360.online`) && PathPrefix(`/db`)"
      service: timeseries
      entryPoints: [web]
      middlewares: [strip-db]

    ws:
      rule: "Host(`ports360.online`) && PathPrefix(`/ws`)"
      service: context-adapter
      entryPoints: [web]

    dashboard:
      rule: "Host(`ports360.online`) && PathPrefix(`/`)"
      service: dashboard
      entryPoints: [web]

  services:
    context-adapter:
      loadBalancer:
        servers:
          - url: http://context-adapter:8010
    twin-core:
      loadBalancer:
        servers:
          - url: http://twin-core:8030
    timeseries:
      loadBalancer:
        servers:
          - url: http://timeseries:8020
    dashboard:
      loadBalancer:
        servers:
          - url: http://dashboard:80

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - /api
    strip-gql:
      stripPrefix:
        prefixes:
          - /gql
    strip-db:
      stripPrefix:
        prefixes:
          - /db
