http:
  routers:
    api:
      rule: "Host(`ports360.optimainterface.com`) && PathPrefix(`/api`)"
      service: context-adapter
      entryPoints:
        - websecure
      tls: {}
    gql:
      rule: "Host(`ports360.optimainterface.com`) && PathPrefix(`/gql`)"
      service: twin-core
      entryPoints:
        - websecure
      tls: {}
    db:
      rule: "Host(`ports360.optimainterface.com`) && PathPrefix(`/db`)"
      service: timeseries
      entryPoints:
        - websecure
      tls: {}
    dashboard:
      rule: "Host(`ports360.optimainterface.com`) && PathPrefix(`/`)"
      service: dashboard
      entryPoints:
        - websecure
      tls: {}
  services:
    context-adapter:
      loadBalancer:
        servers:
          - url: http://context-adapter:8010
    twin-core:
      loadBalancer:
        servers:
          - url: http://twin-core:8030
    timeseries:
      loadBalancer:
        servers:
          - url: http://timeseries:8020
    dashboard:
      loadBalancer:
        servers:
          - url: http://dashboard:80
tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile: /certs/local.key
