entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8081"

providers:
  file:
    filename: /etc/traefik/dynamic.yml
metrics:
  prometheus: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@optimainterface.com
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
