name: CD
on:
  push:
    branches: [main]
    paths:
      - 'services/**'
      - 'tools/**'
      - 'ui/**'
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [services/template_service,
                  services/context_adapter,
                  tools/sensor_sim,
                  services/timeseries,
                  services/twin_core,
                  ui/dashboard]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          visibility: public
      - name: Set lower-case repository name
        run: echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ env.REPOSITORY }}/${{ matrix.context }}:${{ github.sha }},
                ghcr.io/${{ env.REPOSITORY }}/${{ matrix.context }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/ports-360
            git pull
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f

