name: CI

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: >-
          --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
      - name: Install sensor simulator requirements
        run: pip install -r tools/sensor_sim/requirements.txt
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Black format check
        run: black --check .
      - name: Ruff lint
        run: ruff check .
      - name: Run migrations
        run: alembic -c services/timeseries/alembic.ini upgrade head
      - name: Run tests
        run: pytest -q
      - name: Snyk scan
        uses: snyk/actions@v3
        with:
          command: test --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Build and run compose
        run: |
          docker compose up -d --build
          docker compose ps

  build_dashboard:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/dashboard
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - run: npm run test -- --run
